### ISSUE TITLE
LDAP debug mode in slurm-web rest api

### ISSUE THREAD

**Issue by zaihan** [edf-hpc/slurm-web#100]
Hello,

I was wondering if there is an option in slurm-web rest api configuration file which permits/helps to debug LDAP connexion issues?

(We have Active Directory as domain controller)
Regards

Tina R.

**Comment by rezib** [comment]
Hi @zaihan,

The REST API reports its logs and the eventual calltraces when it crashes in the HTTP server errors logs. If you're using Apache and Debian, check `/var/log/apache2/error.log`.

You can also try running the API in foreground with:

```
python /usr/share/slurm-web/restapi/slurmrestapi.py
```

This way you'll also be able to add `print()` statements if needed.

**Comment by zaihan** [comment]
Hi @rezib,
I'm already using the file /var/log/apache2/error.log. 
I've the following error message:
[Tue Mar 01 11:20:51.543918 2016] [wsgi:error] [pid 4843:tid 140249693398784] Authentication failed: username or password is incorrect.

I want to debug it. As we have some OU in our AD architecture may be the problem is there.

Using the API in foreground, I have more outputs.
root@vprd-opci0032:~# python /usr/share/slurm-web/restapi/slurmrestapi.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 136-447-172


Regards,

**Comment by rezib** [comment]
You must configure your dashboard (check your `clusters.config.js`) to use your `localhost:5000` API. Check:

http://edf-hpc.github.io/slurm-web/installation.html#clusters-clusters-config-js

**Comment by rezib** [comment]
Hey @zaihan,

Did you finally succeed in making slurm-web work with your LDAP server?

**Comment by zaihan** [comment]
Hi @rezib,

I've passed so much times to get a python-slurm deb package fully working with Slurm 14.03 under Debian 8. 
Regarding the LDAP connexion, our AD achitecture is much complex and I still have difficulty to put the correct Active Directory DN as slurm-web restapi parameters.
Currently, I'm no longer working on this subject. So, I think the question can be closed. 

Thank you so much for your help.

**Comment by rezib** [comment]
OK @zaihan, I'm closing it.

If you'd like some more help, do not hesitate to either open a new issue or ask me directly. It seems we're working quite close one another, we can eventually meet some day to check what's going on with your AD.

Bye
