### ISSUE TITLE
Add handling of 'MAINT' node state

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/slurm-web#101]
During maintenances, the node state is not displayed correctly in the racks view:

~~~
{
  "cn208": {
    "features": [], 
    "weight": 1, 
    "energy": {
      "current_watts": 0, 
      "consumed_energy": 0, 
      "base_consumed_energy": 0, 
      "previous_consumed_energy": 0, 
      "base_watts": 0
    }, 
    "cpus": 16, 
    "alloc_memory": 0, 
    "cpu_spec_list": [], 
    "owner": 4294967294, 
    "gres_drain": [], 
    "real_memory": 64256, 
    "tmp_disk": 0, 
    "slurmd_start_time": 1460474022, 
    "reason_time": 0, 
    "sockets": 2, 
    "state": "MAINT", 
    "version": "15.08", 
    "node_hostname": "cn208", 
    "total_cpus": 16, 
    "power_mgmt": {}, 
    "core_spec_cnt": 0, 
    "err_cpus": 0, 
    "reason": null, 
    "alloc_cpus": 0, 
    "threads": 1, 
    "boot_time": 1460471156, 
    "cores": 8, 
    "reason_uid": 4294967294, 
    "node_addr": "cn208", 
    "arch": "x86_64", 
    "name": "cn208", 
    "boards": 1, 
    "gres": [], 
    "free_mem": 63221, 
    "tres_fmt_str": "cpu=16,mem=64256", 
    "gres_used": [], 
    "mem_spec_limit": 0, 
    "os": "Linux", 
    "cpu_load": 4
  }, 
~~~

**Comment by Lorel** [comment]
I don't think that this state has ever been handled:
https://github.com/edf-hpc/slurm-web/blob/master/js/draw/colors.js#L51-L91

Add this case in the code above should do the job:
- https://github.com/edf-hpc/slurm-web/blob/4d25f4dac2ab222726133c94ffbe4f4c41525e17/js/draw/2d-draw.js#L391
- https://github.com/edf-hpc/slurm-web/blob/4d25f4dac2ab222726133c94ffbe4f4c41525e17/js/draw/3d-draw.js#L427

The corresponding color has to be added in both of color config files:
- https://github.com/edf-hpc/slurm-web/blob/4d25f4dac2ab222726133c94ffbe4f4c41525e17/conf/dashboard/2d.colors.config.json
- https://github.com/edf-hpc/slurm-web/blob/4d25f4dac2ab222726133c94ffbe4f4c41525e17/conf/dashboard/3d.colors.config.json

**Comment by hmlth** [comment]
Thanks for the info. I'm tagging this as enhancement, since it probably never worked. This is not an often seen state, so this is not a big issue.

**Comment by Lorel** [comment]
You're welcome
I can handle it as soon I've got a bit of time
