### ISSUE TITLE
Debian 8 missing packages

### ISSUE THREAD

**Issue by datakid** [edf-hpc/slurm-web#130]
Just trying to see if I can get the Debian source to install, am coming across issues.

Does node need to be installed?

I'm currently getting the error 

`dpkg-checkbuilddeps: Unmet build dependencies: node-opentypejs (>> 0.4.3-1)`

but there's no package node-opentypejs in any of the repos that I can find?

I've tried just downloading opentype.js and putting it in /usr/lib/nodejs but that didn't work ?

```
user@laptop:~/src/slurm-web$ sudo debuild -us -uc
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage:` warning: using a gain-root-command while being root
dpkg-buildpackage: source package slurm-web
dpkg-buildpackage: source version 2.0.0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Rémi Palancher <remi-externe.palancher@edf.fr>
 dpkg-source --before-build slurm-web
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: node-opentypejs (>> 0.4.3-1)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by rezib** [comment]
This package is not yet available in Debian, we've packaged it ourselves (still in our pending TODOs to upload it in Debian). Code is here:
https://github.com/edf-hpc/opentypejs

@ana just uploaded the missing binary packages under the link in the wiki:
https://github.com/edf-hpc/slurm-web/wiki

You can find all needed packages not yet available in debian right there:
https://people.debian.org/~ana/slurmweb/

**Comment by rezib** [comment]
I guess this one can be closed.

**Comment by s0nghuiming** [comment]
Hi master.
Many dependency issues during installation on ubuntu 16.04.
Do you have any advise on what distribution of ubuntu should be used?

**Comment by alarcher** [comment]
It is a pity your documentation does not mention that some "Debian" packages are actually not provided by official repositories. You would probably attract more users if the installation process was more straightforward :)

**Comment by AlexTMjugador** [comment]
When using the sicibian.org repository linked to in the wiki, it's also necessary to add its APT key:

```
wget -qO - https://scibian.org/repo/scibian-auto-keyring.pub | sudo apt-key add -
```

This is an obvious requirement, but it'd be convenient that it's mentioned in the documentation.
