### ISSUE TITLE
PySLURM expects a string in parameter of job.find_id()

### ISSUE THREAD

**Issue by rezib** [edf-hpc/slurm-web#138]
PySLURM API of job find_id() method has changed lately with this commit:
https://github.com/PySlurm/pyslurm/commit/5423318ac29473af587a6a27a4b4f130d107e592

Slurm-web uses this method here:
https://github.com/edf-hpc/slurm-web/blob/master/rest/slurmrestapi.py#L156

**Comment by vejmarie** [comment]
This can be easily fixed by doing this

@app.route('/job/<job_id>', methods=['POST', 'OPTIONS'])
@crossdomain(origin=origins, methods=['POST'],
             headers=['Accept', 'Content-Type', 'X-Requested-With'])
@authentication_verify()
@cache()
def show_job(job_id):
    job = pyslurm.job().find_id(job_id)
    fill_job_user(job[0])
    return job[0]

Into slurmrestapi.py. This is how I made it worked.

**Comment by vejmarie** [comment]
I made this changed but it implied another issue which I don't remember exactly with 16.05. Let me recheck that

**Comment by rezib** [comment]
Hey @vejmarie, please let me know if you encounter bug with this patch. I prefer this one over yours as it checks the presence of the argument and its type in the route and therefore can handle the error if not properly set.

**Comment by rezib** [comment]
PySLURM `find_id()` actually returns a list, with one element if the job is not a job array. Re-open to fix that properly.

**Comment by rezib** [comment]
Fixed with f1884a0.
