### ISSUE TITLE
"Big" nodes misdrawed in JobMaps

### ISSUE THREAD

**Issue by fmdm** [edf-hpc/slurm-web#147]
When defining a node with height="6" in racks.xml, it misdrawed in the "Job maps" view.
![capture-5](https://cloud.githubusercontent.com/assets/5095415/20803340/21f06e2c-b7ef-11e6-912f-acee93a7620c.png)

**Comment by rezib** [comment]
I can see the LED is missing on the node, do you see another bug?

**Comment by fmdm** [comment]
I was thinking the repartition of the cpus in the node was not ideal, but it seems there's no "good" position.
So we can close this issue.
