### ISSUE TITLE
3D view: Node with 64 cores badly rendered

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/slurm-web#152]
```
<nodetype id="bullxS" model="Bull bullx S" height="6" width="1" />
```

Rendering is fine in the jobsmap.
![jobsmap](https://cloud.githubusercontent.com/assets/11946481/22297548/f351efc8-e31d-11e6-8323-fd39b29fe78a.png)
![3dview](https://cloud.githubusercontent.com/assets/11946481/22297549/f35a4128-e31d-11e6-8768-c56efd585634.png)

**Comment by LaanstraGJ** [comment]
Had the same problem....
Solved it by modifying js/draw/3d-draw.js (this.addCores)
//      if (row / column === 1) {
//        cpuDimensions = Math.min(width, height);
//        cpuDepth = nodeWidth * config.CPUDEPTH;
//      } else {
        cpuDimensions = Math.min(height / row, width / column);
        cpuDepth = nodeWidth * config.CPUDEPTH;
//      }
