### ISSUE TITLE
docker - munged: Error: Found pid 32 bound to socket "/var/run/munge/munge.socket.2"

### ISSUE THREAD

**Issue by wccropper** [edf-hpc/slurm-web#168]
The docker seems to be ready to work, except this error.

**Comment by wccropper** [comment]
for clarity, this is latest docker release on CentOS 7.3 host

**Comment by rbokhorst** [comment]
Adding -F to munged fixed it for me, in the container edit file /etc/service/munge/run: 
```
#!/bin/bash
set -e

mkdir -p /var/run/munge
chown munge: /var/{log,lib,run}/munge
exec /sbin/setuser munge /usr/sbin/munged -F
```

**Comment by manner** [comment]
Adding -f (--force) worked for me.
