### ISSUE TITLE
Dockerfile - empty webpage

### ISSUE THREAD

**Issue by samvandensteen** [edf-hpc/slurm-web#192]
I seem to have the same problems as the users in issue 188 and 189, when starting the docker I get the same empty web page, but neither of those contain a final solution. I have not modified any of the configuration files except for disabling LDAP authentication since everything runs in an internal network anyway.

I wonder whether this has anything to do with the mounts in the run.sh file? My slurm configuration files are in /usr/local/etc which is the default I think.

I'm running slurm 17.11.2, so following issue 189, I tried setting ENV SLURM_VER = 17.11.0 in the Dockerfile, but then I'm getting this error:
```
INFO:root:Info: Build - Deteched Slurm include file version - 0x0f0807 (15.08.07)
ERROR:root:Fatal: Build - Incorrect slurm version detected, require Slurm-17.11.00 to slurm-17.11.03
```
It looks like this issue is related to the PySlurm version, but I don't know how to solve it.

Attaching to the docker container just shows a blinking cursor and no output / console (note that I had to add -F in the munge.sh script following issue 168).

**Comment by rezib** [comment]
Are you sure you're running slurm 17.11.2 inside your docker environment? The PySLURM `setup.py` detects Slurm 15.08.07. Beware that Slurm headers are installed using the distribution packages by the `Dockerfile` : https://github.com/edf-hpc/slurm-web/blob/master/docker/container/Dockerfile#L50

**Comment by samvandensteen** [comment]
Okay, this explains my mistake. I have never used Docker, but I thought it shared kernel + libraries of the host OS. Thus, I was under the impression that PySLURM in the container could communicate with a natively installed SLURM version.

I'll have to think about whether it's feasible to modify the whole cluster for this to work because in our case jobs are actually VM's running simulations etc and we have a complete scripts framework that communicate with a native SLURM installation.

Thanks!
