### ISSUE TITLE
CentOS7 

### ISSUE THREAD

**Issue by enlznep** [edf-hpc/slurm-web#200]
I really wanted to install slurm-web package in CentOS7 but I can't find the best way to install it. I tried the docker container but it failed during the building process (Step 15/29). Is there any best instruction in installing it?

**Comment by nichoice** [comment]
i think installation in centos is simpler than docker

**Comment by mehdid** [comment]
FWIW, if some user could contribute with a procedure to get slurm-web running on CentOS or any other RPM based Linux distribution, we would be more than grateful :-) and we would publish this procedure as part of slurm-web's documentation.

**Comment by alistair4267** [comment]
Hi Guys

More than happy to help with getting slurm-web running on CentOS. 

Cheers
Alistair

**Comment by antanasb** [comment]
Hello,
is there progress in this matter?
Some directions or examples?

**Comment by nichoice** [comment]
yes



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Antanas"<notifications@github.com&gt;; 
发送时间: 2019年11月26日(星期二) 晚上10:25
收件人: "edf-hpc/slurm-web"<slurm-web@noreply.github.com&gt;; 
抄送: "Nicholas"<798254259@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [edf-hpc/slurm-web] CentOS7  (#200)




您好，
 这件事有进展吗？
 一些指示或示例？
 
— 
您收到此评论是因为您发表了评论。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by antanasb** [comment]
Hi Nichoice,
do you followed this comment – https://github.com/edf-hpc/slurm-web/issues/51#issuecomment-124551543 ?

**Comment by levidd** [comment]
I am struggling to get slurm-web working with CentOS. I followed a strategy that I found here [https://github.com/edf-hpc/slurm-web/issues/169](issue 169),  but it fails. Some errors look like


Uncaught TypeError: Cannot read property 'factory' of undefined
    at init (index.js:97)
    at fn (require.min.js:1395)
    at Object.execCb (require.min.js:1696)
    at Module.check (require.min.js:883)
    at Module.enable (require.min.js:1176)
    at Module.init (require.min.js:788)
    at callGetModule (require.min.js:1203)
    at Object.completeLoad (require.min.js:1611)
    at HTMLScriptElement.onScriptLoad (require.min.js:1717)

**Comment by bviviano** [comment]
> I am struggling to get slurm-web working with CentOS. I followed a strategy that I found here [https://github.com/[/issues/169](https://github.com/edf-hpc/slurm-web/issues/169)](issue 169), but it fails. Some errors look like

Your issues are likely because you have the wrong versions of the dependencies.  I just completed an upgrade from 2.2.2 to 2.2.5 under RHEL 7.7 and it's working fine, but I didn't update any of the dependencies (jquery, bootstrap*, d3, etc) between 2.2.2 and 2.2.5.

**Comment by rezib** [comment]
Hi everyone, I just released v2.4.0 with a spec file to build RPM for el8. Let me know if you see any reason to re-open this issue.
