### ISSUE TITLE
Error : cluster.config.json cannot be loaded..

### ISSUE THREAD

**Issue by IMTejesh95** [edf-hpc/slurm-web#201]
![screenshot from 2018-12-11 17-50-00](https://user-images.githubusercontent.com/33658194/49800378-5a1e5500-fd6d-11e8-8870-bdaa41e8fad7.png)
I am getting this error!
I have installed slurm-web on Ubuntu 18.04 machine.

**Comment by mehdid** [comment]
It seems you are missing a clusters.config.json file. Do you confirm?

An example for content is given here: https://edf-hpc.github.io/slurm-web/installation.html#clusters-clusters-config-js

**Comment by mehdid** [comment]
Any news?
