### ISSUE TITLE
repository docker.io/slurm-web not found:

### ISSUE THREAD

**Issue by dhilst** [edf-hpc/slurm-web#202]
Can't found docker image, it has gone? Do I need to login in docker to get the image

regards,

**Comment by dhilst** [comment]
![image](https://user-images.githubusercontent.com/392820/51786181-0a8ebf80-2148-11e9-9001-25213e82f321.png)

**Comment by kevindice** [comment]
The Docker image isn't yet published to Dockerhub, but you can build by running
`docker build -t slurm-web .`
inside of the `slurm-web/docker/container` directory:  https://github.com/edf-hpc/slurm-web/tree/master/docker/container

**Comment by dhilst** [comment]
Ohh I see, excuse me for opening this, I'm closing it!
