### ISSUE TITLE
Problem with css

### ISSUE THREAD

**Issue by diogocalgaro** [edf-hpc/slurm-web#204]
Hi,

I have followed the bviviano instructions on the issue #169 and managed to get Slurm-web working on Centos 7.6, but somehow I think the css is not loading correctly.

Look at the screenshot:

![screenshot-jobs-edited](https://user-images.githubusercontent.com/8246699/55821411-d8002c00-5ad3-11e9-97a1-388e82891e54.png)

The header is different from the images I've found on the site. The menu is in a list format and is white on white, so it is hard to see.

I didn't find any warning of missing files in chrome console or in the apache access_log. 

Can you help me find the problem?

Thanks a lot.

**Comment by adamya21** [comment]
hi @diogocalgaro Can you pls tell me the version of packages you are using currently 

py 2.7
pyslurm  = 19.05.00
bootstrap = 4.3.1  
bootstrap-tagsinput
bootstrap-typeahead
async
d3 =v3.5.17
requirejs = 2.3.6
jquery = 2.2.4  
jquery-tablesorter  = 2.17.8 
jquery-flot = 0.8.3 
handlebars = v4.1.1
Three= master.zip (latest)

But it's not working out for me I'm getting blue arc loading sign . What should i do?

**Comment by diogocalgaro** [comment]
Sorry, I'm not using Slurm-web anymore. I don't remember the package versions.

**Comment by marks221b** [comment]
> hi @diogocalgaro Can you pls tell me the version of packages you are using currently
> 
> Mine is below py 2.7 pyslurm = 19.05.00 bootstrap = 4.3.1 bootstrap-tagsinput bootstrap-typeahead async d3 =v3.5.17 requirejs = 2.3.6 jquery = 2.2.4 jquery-tablesorter = 2.17.8 jquery-flot = 0.8.3 handlebars = v4.1.1 Three= master.zip (latest)
> 
> But it's not working out for me I'm getting blue arc loading sign . What should i do?

hey pal ,I would really appreciate if there is a tutorial on running slurm-web on centos7
