### ISSUE TITLE
is this project active?

### ISSUE THREAD

**Issue by gmaggi** [edf-hpc/slurm-web#216]
Hi,

I just found this project, before proceeding to install it, I'd like to know whether issues and questions are still answered and also if the project is currently maintained?

Thanks,
Giuliano.

**Comment by rezib** [comment]
Hi @gmaggi,

The project is still maintained, the software is used in production on EDF clusters with recent versions of Slurm (20.11), on RHEL8 and various Debian versions.

Last years efforts have been focused on porting the software to new versions of its ecosystem (python, slurm, etc), few efforts have been made to develop new features. Issues and questions are answered during spare time, which is scarse obviously :)

We have a plan to invest more in this project in the following months, with a new roadmap (slurmrestd, advanced JS framework), CI, documented/supported installation methods, and so on. Stay tuned!
