### ISSUE TITLE
Slurm version compatibility

### ISSUE THREAD

**Issue by philshem** [edf-hpc/slurm-web#220]
Is there a known and tested compatibility chart for different Slurm versions?

(yes, we are using an old version ;)

**Comment by rezib** [comment]
Hello @philshem,

Slurm-web by itself is not really tight to any specific Slurm version, the code is rather generic and might work with last 5 or 6 major Slurm versions.

The real concern is more about PySlurm, the library used by Slurm-web to interact with Slurm: https://github.com/PySlurm/pyslurm

One PySlurm version supports only one major Slurm version. If you end up having a working PySlurm for your Slurm version, Slurm-web would probably be satisfied with it.

**Comment by philshem** [comment]
Thanks!
