### ISSUE TITLE
Show percentage of allocated cores on Jobs page

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#4]
Like vishnu did. :-)

**Comment by rezib** [comment]
What pourcentage are you talking about?

- The percentage all cores of the supercomputer that are currently allocated by jobs?
- The percentage of cores of a job that are **actually** used by the processes of the job?
- Another thing?

**Comment by mehdid** [comment]
I don't know why you think it could be 2 or 3... :) I'm adjusting the bug's title accordingly.
