### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by Lorel** [edf-hpc/slurm-web#48]
The authentication system must allow to use an LDAP server

3 roles are expected :
* `all` : unauthenticated user
  The access must be customizable with 2 different values :
  * no access (login form only)
  * RO rights on the whole interface (except jobs exec paths)
* `user` : `all` user's rights + jobs exec paths of the current user
* `admin` : `user` user's rights + all jobs exec paths

The role configuration file could look like this :
```
# The `all` role could have 2 values:
# - none, restrict access to authenticated users only
# - all, free access to non-sensible data
all: none|all
# The roles members can be defined with a list of groups (whose names
are prefixed by @)
# and logins. The %c in group names is substituted by the cluster name.
users: @cl-%c-users
admin: @cl-%c-admin,@cl-%c-boss,login-boss2
```

**Comment by rezib** [comment]
I am currently testing the current HEAD of 2.0 branch on a EDF cluster and I'm having a first issue with this feature: I have `all = all` in the `[roles]` section of my `restapi.conf` file but when I access to the dashboard w/o login I get basically nothing (blank page except the menu at the top).

I'm not sure that's expected, right? :)

**Comment by Lorel** [comment]
right, that's not expected :)

everything works fine on chrome
which browser are you using ?
