### ISSUE TITLE
Time displayed for running jobs in "Start" column is 1hour too old

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/slurm-web#54]
In the list the time "Since XXh YYmin ZZs" is always 1 hour too long.

In the screenshot, the job started at 15:17:8, and is displayed to be more than 1hour old at 15h17. The local computer is also at GMT+0100.

![bugreport-slurmweba](https://cloud.githubusercontent.com/assets/11946481/10883945/8a37c27a-8175-11e5-9403-62cbcd8c2018.png)

**Comment by Lorel** [comment]
Bug v1
