### ISSUE TITLE
Dashboard cluster name in head title with default conf should be actual cluster name, not local

### ISSUE THREAD

**Issue by rezib** [edf-hpc/slurm-web#61]
With default dashboard configuration where there's only one backend API on local server, the cluster name in head title is 'local'. This should be the actual cluster as returned by the local backend API.

**Comment by rezib** [comment]
The sensible thing here is that /cluster requires auth.

I can see 3 ways to implement this feature:

1/ Disable auth on `/cluster` and call it in `selectCluster()`
2/ Accept this feature does not work if auth is enable on local cluster
3/ Give cluster name in `/authentication`, by calling `get_cluster()` in `authentification()` to get caching benefit

**Comment by rezib** [comment]
I vote for 3/, and try to implement it then.

**Comment by rezib** [comment]
4/ Merge `/authentication` and `/cluster`, which is roughly equivalent to 1/

**Comment by Lorel** [comment]
I vote for 4/
authentication's datas are specific to a cluster
so all informations about cluster and authentication should be retrieved at the same time

**Comment by rezib** [comment]
I vote for 4/ too.

**Comment by rezib** [comment]
Let me close them with commit msg.
