### ISSUE TITLE
Rack view: Node names should adapt wrt. to their geometry

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#72]
Node names should be drawn vertically or horizontally depending on nodes geometry and to fit the best in the allocated space. The string will be shown inside the rectangle drawn for the node.

**Comment by robink** [comment]
Penser à changer la couleur, faire une proposition de passer les textes en blanc sur fond bleu foncé

Mettre .... quand les noms sont trop long, tooltip à ajouter pour avoir le nom complet au mouseover.

Enlever le début du nom en mettant les ... car l'info la plus importante est à la fin, c'est le numéro du noeud

**Comment by rezib** [comment]
This may be related to this commit: we're facing a new regression where nodes are drawn 2U higher than their positions in the racks.xml file.

**Comment by rezib** [comment]
Also, with the change in racks/nodes size, some nodes appear a bit blurry because the lines are drawn between 2 pixels and the canvas element does interpolation. Maybe you can't see it with HDPI on your macs but I can clearly see it on my screen :)

**Comment by rezib** [comment]
For the regression on nodes positions, it is actually OK if we consider the unit at the bottom is posy 0. This must be made clear in the doc though.

**Comment by rezib** [comment]
With this `racks.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rackmap SYSTEM "/usr/share/slurm-web/restapi/schema/dtd/racks.dtd">
<rackmap>
  <nodetypes>
    <nodetype id="x3550m4" model="IBM System 3550 M4" height="1" width="1" />
    <nodetype id="x3550m4_2" model="IBM System 3550 M4" height="4" width="0.2" />
  </nodetypes>

  <racks posx="0" posy="0" width="10" depth="10">
    <racksrow posx="0">

      <!-- Rack C8-E10 -->
      <rack id="C8-E10" posy="0">
        <nodes>
          <nodeset id="adcn[01-07]" posy="7" type="x3550m4" />
          <nodeset id="adcn[08-12]" posy="15" type="x3550m4_2" />
        </nodes>
      </rack>

    </racksrow>
  </racks>
</rackmap>
```

I'm seeing this:
![weird_geometry](https://cloud.githubusercontent.com/assets/1862918/12911533/8053846a-cf13-11e5-9754-a1f77d41b657.png)

I would have expected the nodes `adcn[08-12]` to be above `adcn07`. What is the nodes' `posy`?

**Comment by rezib** [comment]
In the jobsmap, the cores drawn should also adapt to the geometry:
![geometry_cores](https://cloud.githubusercontent.com/assets/1862918/12911600/f3f3bdb8-cf13-11e5-972b-e068b3d8f9ed.png)

**Comment by julienvdt** [comment]
Hello Remi,

"In the jobsmap, the cores drawn should also adapt to the geometry"

Ceci est un bug lié à la V1 non ? car quand on a récupéré le code avant la V1, cela ne fonctionnait pas de mémoire. Te souviens tu ? A ta dispo pour en discuter.

**Comment by rezib** [comment]
Hello @julienvdt,

At the time of the version 1, I developed a logic to find the best cores matrix sizes depending on nodes dimensions: https://github.com/edf-hpc/slurm-web/blob/1b00e69826b62cfe592e2ed564d2395c78c5f391/js/slurm-dashboard.js#L942

So I think it used to work some time.

**Comment by Lorel** [comment]
This logic only gives the best decomposition, but this is not oriented at all, no notion about whether the group of nodes have to been oriented as a landscape or a portrait
For example, you can test it quickly in your console for a 28 height cores node with a width of 120px and a height for 54px, compared to one with a width of 70px and a height for 104px :

```
best_factor(120, 54, 28)
[4, 7]

best_factor(70, 104, 28)
[4, 7]
```

There we see that the code has not any consideration about the orientation of the node. So the v1 is not able to handle these cases.

Finally, to consider the orientation, here is the expected comportment of https://github.com/edf-hpc/slurm-web/blob/1b00e69826b62cfe592e2ed564d2395c78c5f391/js/slurm-dashboard.js#L942 :

```
best_factor(120, 54, 28)
[4, 7]

best_factor(70, 104, 28)
[7, 4]
```

So it has to be fixed

**Comment by rezib** [comment]
We're still expecting the racks/jobmaps views to get back to the previous sizes.

**Comment by Lorel** [comment]
@rezib
racks/jobmaps default size has been restored to the previous one with 2415780bdf194111623552aa38b1fd30fedf6ce8

**Comment by rezib** [comment]
There is still a regression here...

Here is the current look: 
![racks_wrong_size](https://cloud.githubusercontent.com/assets/1862918/15602147/bfe34554-23f3-11e6-92e2-e600ddc5a9bc.png)
Here is the previous look: http://edf-hpc.github.io/slurm-web/_images/screenshot_jobsmap.png

The racks size ratios have changed, and the racks look bigger than before. Also, I guess we can remove the whitespaces between the racks now that the nodenames are not printed anymore.

**Comment by rezib** [comment]
Finally OK with PR #117 and d0c73e4.
