### ISSUE TITLE
Filter jobs on selected QOS from QOS view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#75]
On the QOS view, a clic on a QOS name should make Jobs view appear and use the clicked QOS as a filter.

**Comment by rezib** [comment]
1 bug seen: when I filter on a QOS this wa

**Comment by Aenohe** [comment]
Error: Fixed see commit [11498af](https://github.com/edf-hpc/slurm-web/commit/11498af8d9951b1ef4e948f63238033b2ab7f062)

**Comment by rezib** [comment]
Validation locked due to bug reported in #83.

**Comment by rezib** [comment]
It's OK.
