### ISSUE TITLE
Merge "Reservation" and "Partition" views

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#76]
Partition view is kept as a principal view. Reservations, if any, are shown below the list of partitions. If there are no reservations configured, the web interface should make it explicit.

**Comment by rezib** [comment]
Then, find a better name for this view since users won't figure out why reservations are shown in the "partitions" view.

**Comment by mehdid** [comment]
Suggestions? :-) Or should we postpone this issue for a later release until we have a suitable name?

**Comment by rezib** [comment]
I really suck at name, but what about "platform"?

**Comment by robink** [comment]
Suggestion : Bouton "other" avec les vues pas souvent utilisées, avec dropdown, bandeau sur le droite vertical. A définir suite à reflexion .

Plus utile, de ce fait, de fusionner les vues.

**Comment by mehdid** [comment]
Il me semblait que, pendant la réunion, nous avions statué sur l'abandon de la fusion des deux vues. A la place, un bouton apparaiterait en haut et à droite si l'espace disponible n'est pas suffisant pour afficher toutes les vues. Si cela n'est pas réalisable, alors la solution de Robin conviendrait.

**Comment by rezib** [comment]
Must choose between 2 behaviours: 

1. *static* drop down menu with *low-priority* views explicitely sets in conf (like in the screencast), as soon as not enough width.
2. *dynamic* drop down menu with views consecutively dropped in the menu, starting from the right, as long as the browser width decreases.

With the later, we should eventually redefine views order.

**Comment by mehdid** [comment]
We are definitely going with scenario 2 (dynamic menu), but I don't see an urge to redefine the order of the views. It can be done later when this feature is developed and stabilized.

**Comment by rezib** [comment]
We're still expecting development of the 2nd behavior here.

**Comment by rezib** [comment]
Thank you for the last commit. There is still a bug when the window size is decreased down to the apparition of the "sandwich" and then increased again. Sometimes, when doing this, some views do not come back in the menu... Can you please fix this bug?

**Comment by rezib** [comment]
Thank you for for the fix, it's OK now.
