### ISSUE TITLE
Automatic login

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#77]
When enabled, this feature should make SlurmWeb try to connect to all configured clusters on the dashboard, even if other clusters are not explicitly selected by the user.

**Comment by robink** [comment]
Seulement quand l'option est activée, login automatique quand on se reconnecte à un autre cluster par exemple.

**Comment by rezib** [comment]
Has the doc been updated to explain how to enable/disable this feature? I just can't find where.

**Comment by rezib** [comment]
We're on a configuration with 2 clusters on the same dashboard, cluster A w/o auth and cluster B w/ auth.

When we try to connect with user/login (with correct creds) on cluster B, it systematically fails the first time with: "Error: your login / password doesn't match." Then, when we click once more on login button (with the same credentials in the form), it's OK.

**Comment by rezib** [comment]
When autologin is on, the logout must done on all clusters as well.

**Comment by rezib** [comment]
I have those settings in my `config.json`:

 ```
# cat /etc/slurm-web/dashboard/config.json
{
  "STARTPAGE": "jobs",
  "REFRESH": 30000,
  "MAXNODESLENGTH": 25,
  "AUTOLOGIN": false
}
```

But autologin is still enabled on my dashboard. There is something weird here...

**Comment by Lorel** [comment]
@rezib : and what about the response of `/slurm-web-conf/config.json` in your browser ?

**Comment by rezib** [comment]
Right, it was still *true*... To get this into effect, I actually needed to:

1/ reload the HTTP server,
2/ reload the dashboard in my browser.

I would not have expected such behaviour since `config.json` is a flat file... I think 1/ must be made clear in documentation.

**Comment by Lorel** [comment]
this is about the cache in Apache, not related to slurmweb

**Comment by rezib** [comment]
Please check Flask `SEND_FILE_MAX_AGE_DEFAULT`.

**Comment by rezib** [comment]
#99 open for this purpose.

**Comment by rezib** [comment]
I'm OK with current state.
