### ISSUE TITLE
Create a jobs/nodes view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#8]
https://calcul.crihan.fr/node/13

**Comment by rezib** [comment]
There are missing parts in pyslurm to get the cores allocated to a job on each node. First PR sent: https://github.com/gingergeeks/pyslurm/pull/44

**Comment by rezib** [comment]
Slurm API does not have any function to get the exact list of allocated CPUs on a node for a job. Therefore, I also opened a bug on Slurm to merge patches to add new 2 functions needed for this feature: http://bugs.schedmd.com/show_bug.cgi?id=1575

**Comment by mehdid** [comment]
For this first version of slurm-web, it is enough to have the number of allocated CPUs. No?

**Comment by rezib** [comment]
Well yes, it's up to you @mehdid :)

Anyway, all the needed patches are ready in both Slurm and pyslurm. The advantage of delaying the 2nd part of this feature is that we get time to make these patches (hopefully) merged upstream which is still much better than pending in our patch queues!

So finally yes, I think this a good idea to split this feature in 2 parts and delay the "exact allocated cores" sub-feature to next version.

**Comment by mehdid** [comment]
The advantage of splitting this into two distinct tickets is the ability to deploy slurm-web (v1) on other clusters without needing a patched version of Slurm. Did you need to patch Slurm so far for other reasons than this specific ticket?

**Comment by rezib** [comment]
Nop.

**Comment by rezib** [comment]
Next step in #24.
