### ISSUE TITLE
Asynchronous javascript calls

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#81]
Try to minimize number of synchronous javascript calls made in the code. The idea is to use libjs-async to make asyncrhonous calls and, hopefuly, enhance responsiveness of the web interface.

**Comment by rezib** [comment]
I'm not sure how to test this feature :) All I can say is that I have no problem with it!

**Comment by Aenohe** [comment]
@rezib Cool. You can test in the browser developer tools.

Chrome example:
<img width="1677" alt="screen shot 2016-02-08 at 17 36 07" src="https://cloud.githubusercontent.com/assets/1830348/12892084/b71bc7f2-ce8a-11e5-9da3-81e892afeb11.png">

In the column "timeline - start time'
