### ISSUE TITLE
Optimizations in 3D view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#82]
Current code uses one object by CPU core, etc... This makes moving objects a bit heavy and slow. Merging objects should make it more usable and light.

**Comment by mehdid** [comment]
The following error is seen when testing the 3D View :

TypeError: THREE.PlaneBufferGeometry is not a constructor (dans 3d-draw.js:147).

I guess this is why we're seeing only a black rectangle on the page.

Besides, there is also this warning :

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by rezib** [comment]
Last error fixed with upgrade to three.js r72.
