### ISSUE TITLE
More filters in Jobs view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#83]
More filters can be :
- User names
- User IDs
- Nodes
- Job states
- Start and endtime

**Comment by robink** [comment]
Comportement attendu : Restreindre sur une certaine période, par exemple les jobs qui vont se terminer dans 3 heures, les jobs courts. Par exemple tous les jobs en pending. Mot clef : "ce que l'on va rechercher" comme sur github

**Comment by rezib** [comment]
Exemple for dates/times intervals :

start > 1d
end < 2h

**Comment by rezib** [comment]
Units: s, m, h, d, w, M,  y

**Comment by Lorel** [comment]
filter on hostlist nodesets

**Comment by mehdid** [comment]
Le module NodeSet : https://pythonhosted.org/ClusterShell/ClusterShell.NodeSet-module.html

**Comment by rezib** [comment]
With last commits, when a filter is selected, there is systematically 0 job in the results...

**Comment by rezib** [comment]
Please update the doc to explain usage of this new feature.

**Comment by rezib** [comment]
I still have the same errors even with last patches in `js/utils/tagsinput.js`.

**Comment by rezib** [comment]
It's ok with patches.

**Comment by rezib** [comment]
The JS function `convertNodeset()` shoud not exist. There is an API that has been developed specifically for this purpose in #91. It must be used for this feature.

Also, it seems the doc to use node/cpu filters is missing.

**Comment by rezib** [comment]
It's OK for this feature.
