### ISSUE TITLE
ACLs on views

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#84]
Admins should be able to say which user (or group) has access to which set of views.

**Comment by robink** [comment]
En fonction du login, contrôle sur cluster pour savoir ce qu'il a le droit de voir

**Comment by rezib** [comment]
Please rename "views_acl" section into "acl", it's more lean and clear enough :)

**Comment by rezib** [comment]
With those ACLs:

```
[acl]
gantt = @admin
topology = @admin,rp140c6n
```

Once loggued in, my user account `rp140c6n` does have neither access to gantt and topology views. For gantt, that's ok since I'm not in admin group, but topology, I have have expected the opposite!

**Comment by rezib** [comment]
With multiple clusters with different ACLs, I first login on all clusters and then I reload the dashboard. I'm still loggued in on all clusters and I get access to all views, including the views I should not get access...

**Comment by rezib** [comment]
After thinking about this a bit more, this is weird to control access to views on the REST backend side since views are something specific to the dashboards. This way, I guess the feature is broken by design...

**Comment by Lorel** [comment]
Works perfectly for me, tested with 
```
jobs = rp140c6n
jobsmap = @other
partitions = @admin,rp140c6n
```
Maybe a problem of cache with Apache ? If you change `restapi.conf`, you need to restart Apache to load the new settings

I don't agree with you, rezib, the design is good : ACLs is related to user, so to their authentication, so it depends on the backend, plus it is specific of each cluster

**Comment by rezib** [comment]
Views are a pure dashboard concept, there's nothing like "views" in the backend REST API... Views will evolve with the dashboard, so there is no good reason to control those views in the backend configuration file...

That's true auth is done on backend side (which is fair and required), but authorization and authentication are orthogonal, they are not strictely coupled.

**Comment by rezib** [comment]
It's OK for this issue.
