### ISSUE TITLE
 Filter jobs on selected reservation from Reservation view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#86]
On the Partition view, a clic on a reservation name should make Jobs view appear and use the clicked reservation as a filter.

**Comment by robink** [comment]
Les jobs appartiennent à une réservation, il faut que l'utilisateur le spécifie. Par exemple pour les formations.  Réservation du noeud par un administrateur. On peut créer une réservation sur un cluster en entier pour les maintenances par exemple. Le comportement attendu est lorsque l'on clique sur une ligne réservation , on affiche que les jobs liés à cette réservation. Un job peut être associé à cette réservation. Mock up en attente.

**Comment by rezib** [comment]
It works fine.
