### ISSUE TITLE
Implements a route on the rest API to transform a nodeset in a set of nodes

### ISSUE THREAD

**Issue by Lorel** [edf-hpc/slurm-web#91]
i.e : give `"cluster[1-4]"` and get `["cluster1", "cluster2", "cluster3", "cluster4"]`

use https://pythonhosted.org/ClusterShell/ClusterShell.NodeSet-module.html

**Comment by rezib** [comment]
Must fix #83 to check this feature.

**Comment by rezib** [comment]
It's OK for this feature.
