### ISSUE TITLE
Disable cache on static config files for dashboard conf server

### ISSUE THREAD

**Issue by rezib** [edf-hpc/slurm-web#99]
There is a cache effect on the static JSON files delivered by the dashboard configuration server. It should be disable, so that parameters change could take effect immediately, w/o reload HTTP server.

There's a Flask parameter `SEND_FILE_MAX_AGE_DEFAULT` to control this.

But it must be discussed in EDF internally first.

**Comment by mehdid** [comment]
I don't have strong opinion on this. I'll follow your advice. The only question that should be studied is the impact of lowering the value of SEND_FILE_MAX_AGE_DEFAULT to a minimum value.
